### ISSUE TITLE
runtime.goexit()

### ISSUE THREAD

**Issue by bert2002** [burnt-labs/xion#180]
Hi,
since updating to `0.3.7` (official docker image) we have seen twice that the application dies with the following go errors:

```
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/mempool/v0/reactor.go:284 +0x21f fp=0xc02915e720 sp=0xc02915e600 pc=0x10c09df
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/mempool/v0.(*Reactor).AddPeer.func1()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/mempool/v0/reactor.go:191 +0x1a5 fp=0xc02915e7e0 sp=0xc02915e720 pc=0x10bfda5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.goexit()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc02915e7e8 sp=0xc02915e7e0 pc=0x4c16a1
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | created by github.com/cometbft/cometbft/mempool/v0.(*Reactor).AddPeer in goroutine 52
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/mempool/v0/reactor.go:157 +0xa5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | goroutine 118242064 [select]:
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.gopark(0xc00d182e98?, 0x2?, 0x96?, 0xbf?, 0xc00d182e64?)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc00d182c28 sp=0xc00d182c08 pc=0x48df0e
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.selectgo(0xc00d182e98, 0xc00d182e60, 0xedd89cc35?, 0x0, 0x462c?, 0x1)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/select.go:327 +0x725 fp=0xc00d182d48 sp=0xc00d182c28 pc=0x49e3e5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*peer).metricsReporter(0xc0c763c000)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/peer.go:372 +0xc5 fp=0xc00d182fc8 sp=0xc00d182d48 pc=0xd818e5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*peer).OnStart.func1()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/peer.go:199 +0x25 fp=0xc00d182fe0 sp=0xc00d182fc8 pc=0xd80bc5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.goexit()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc00d182fe8 sp=0xc00d182fe0 pc=0x4c16a1
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | created by github.com/cometbft/cometbft/p2p.(*peer).OnStart in goroutine 118241852
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/peer.go:199 +0x66
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | goroutine 118257445 [sleep]:
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.gopark(0x450ff4188ea15?, 0x75d00b?, 0xf0?, 0xd2?, 0x75ca00?)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc021c8fbc8 sp=0xc021c8fba8 pc=0x48df0e
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | time.Sleep(0x5f5e100)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/time.go:195 +0x125 fp=0xc021c8fc08 sp=0xc021c8fbc8 pc=0x4be4a5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/consensus.(*Reactor).gossipDataForCatchup(0xc006bc0c60, {0x3f0e3d8, 0xc0847fdba0}, 0xc0193e3d40, 0xc0ae718f00, 0x2?, {0x3f37e00, 0xc04e1d9520})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/consensus/reactor.go:698 +0x93d fp=0xc021c8fd70 sp=0xc021c8fc08 pc=0x106529d
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/consensus.(*Reactor).gossipDataRoutine(0xc006bc0c60, {0x3f37e00?, 0xc04e1d9520}, 0xc0053bb2c0?)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/consensus/reactor.go:595 +0x2ee fp=0xc021c8ffb0 sp=0xc021c8fd70 pc=0x1063ece
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/consensus.(*Reactor).AddPeer.func1()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/consensus/reactor.go:203 +0x2c fp=0xc021c8ffe0 sp=0xc021c8ffb0 pc=0x106136c
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.goexit()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc021c8ffe8 sp=0xc021c8ffe0 pc=0x4c16a1
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | created by github.com/cometbft/cometbft/consensus.(*Reactor).AddPeer in goroutine 52
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/consensus/reactor.go:203 +0xf6
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | goroutine 118267249 [sleep]:
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.gopark(0x450ff453c0476?, 0x75d00b?, 0x50?, 0x39?, 0x75ca00?)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc005782bc8 sp=0xc005782ba8 pc=0x48df0e
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | time.Sleep(0x5f5e100)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/time.go:195 +0x125 fp=0xc005782c08 sp=0xc005782bc8 pc=0x4be4a5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/consensus.(*Reactor).gossipDataForCatchup(0xc006bc0c60, {0x3f0e3d8, 0xc07b705a40}, 0xc0193e3d40, 0xc06d4daaa0, 0x100c01f6d3b00?, {0x3f37e00, 0xc14fff9a00})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/consensus/reactor.go:698 +0x93d fp=0xc005782d70 sp=0xc005782c08 pc=0x106529d
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/consensus.(*Reactor).gossipDataRoutine(0xc006bc0c60, {0x3f37e00?, 0xc14fff9a00}, 0xc11dd8f790?)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/consensus/reactor.go:595 +0x2ee fp=0xc005782fb0 sp=0xc005782d70 pc=0x1063ece
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/consensus.(*Reactor).AddPeer.func1()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/consensus/reactor.go:203 +0x2c fp=0xc005782fe0 sp=0xc005782fb0 pc=0x106136c
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.goexit()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc005782fe8 sp=0xc005782fe0 pc=0x4c16a1
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | created by github.com/cometbft/cometbft/consensus.(*Reactor).AddPeer in goroutine 52
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/consensus/reactor.go:203 +0xf6
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | goroutine 118276030 [select]:
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.gopark(0xc00592d588?, 0x2?, 0xc?, 0x24?, 0xc00592d564?)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc00592d410 sp=0xc00592d3f0 pc=0x48df0e
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.selectgo(0xc00592d588, 0xc00592d560, 0x2e7f9c0?, 0x1, 0xc0ce302a80?, 0x1)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/select.go:327 +0x725 fp=0xc00592d530 sp=0xc00592d410 pc=0x49e3e5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p/conn.(*Channel).sendBytes(0xc038f04780, {0xc09387d3a0?, 0x9?, 0xc0ce302a80?})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/conn/connection.go:782 +0x90 fp=0xc00592d5b8 sp=0xc00592d530 pc=0xd40830
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p/conn.(*MConnection).Send(0xc045382000, 0x20, {0xc09387d3a0, 0x9, 0x9})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/conn/connection.go:365 +0x235 fp=0xc00592d630 sp=0xc00592d5b8 pc=0xd3e375
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p/conn.(*MConnection).Send-fm(0xf0?, {0xc09387d3a0?, 0xc098ac6880?, 0x1?})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         <autogenerated>:1 +0x33 fp=0xc00592d668 sp=0xc00592d630 pc=0xd8f733
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*peer).send(0xc08116fba0, 0x20, {0x3f06c30, 0xc098ac6880}, 0xc00592d738)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/peer.go:285 +0x1d1 fp=0xc00592d710 sp=0xc00592d668 pc=0xd81231
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*peer).SendEnvelope(0xc00592d7b0?, {{0x0, 0x0}, {0x3f06c30, 0xc098ac6880}, 0x20})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/peer.go:261 +0x5b fp=0xc00592d758 sp=0xc00592d710 pc=0xd80f3b
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*Switch).BroadcastEnvelope.func1({0x3f37e00?, 0xc08116fba0?})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/switch.go:283 +0x7f fp=0xc00592d7c0 sp=0xc00592d758 pc=0xd8485f
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*Switch).BroadcastEnvelope.func3()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/switch.go:285 +0x2b fp=0xc00592d7e0 sp=0xc00592d7c0 pc=0xd847ab
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.goexit()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc00592d7e8 sp=0xc00592d7e0 pc=0x4c16a1
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | created by github.com/cometbft/cometbft/p2p.(*Switch).BroadcastEnvelope in goroutine 5238
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/switch.go:281 +0x112
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | goroutine 118280243 [select]:
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.gopark(0xc0058e8d88?, 0x2?, 0x0?, 0xa3?, 0xc0058e8d64?)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc0058e8c10 sp=0xc0058e8bf0 pc=0x48df0e
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.selectgo(0xc0058e8d88, 0xc0058e8d60, 0x2e7f9c0?, 0x1, 0xc03ccea2a0?, 0x1)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/select.go:327 +0x725 fp=0xc0058e8d30 sp=0xc0058e8c10 pc=0x49e3e5
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p/conn.(*Channel).sendBytes(0xc12fc23900, {0xc089f382f0?, 0xb?, 0xc03ccea2a0?})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/conn/connection.go:782 +0x90 fp=0xc0058e8db8 sp=0xc0058e8d30 pc=0xd40830
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p/conn.(*MConnection).Send(0xc0360a9600, 0x20, {0xc089f382f0, 0xb, 0xb})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/conn/connection.go:365 +0x235 fp=0xc0058e8e30 sp=0xc0058e8db8 pc=0xd3e375
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p/conn.(*MConnection).Send-fm(0xf0?, {0xc089f382f0?, 0xc03ea30930?, 0x1?})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         <autogenerated>:1 +0x33 fp=0xc0058e8e68 sp=0xc0058e8e30 pc=0xd8f733
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*peer).send(0xc09880a0d0, 0x20, {0x3f06c60, 0xc03ea30930}, 0xc0058e8f38)
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/peer.go:285 +0x1d1 fp=0xc0058e8f10 sp=0xc0058e8e68 pc=0xd81231
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*peer).SendEnvelope(0xc0058e8f20?, {{0x0, 0x0}, {0x3f06c60, 0xc03ea30930}, 0x20})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/peer.go:261 +0x5b fp=0xc0058e8f58 sp=0xc0058e8f10 pc=0xd80f3b
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*Switch).BroadcastEnvelope.func1({0x3f37e00?, 0xc09880a0d0?})
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/switch.go:283 +0x7f fp=0xc0058e8fc0 sp=0xc0058e8f58 pc=0xd8485f
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | github.com/cometbft/cometbft/p2p.(*Switch).BroadcastEnvelope.func3()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/p2p/switch.go:285 +0x2b fp=0xc0058e8fe0 sp=0xc0058e8fc0 pc=0xd847ab
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | runtime.goexit()
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc0058e8fe8 sp=0xc0058e8fe0 pc=0x4c16a1
Mar 18 05:48:02 node xion[103735]: xion-cosmos-1  | created by github.com/cometbft/cometbft/p2p.(*Switch).BroadcastEnvelope in goroutine 5238
```

We did not experience this in previous version (`0.3.4` or `0.3.5`).

Anyone experience the same?

Thanks,
bert

**Comment by justinbarry** [comment]
Docker image should be updated. Please try again and report back if the issue persists.

**Comment by bert2002** [comment]
@justinbarry will there be a new tag for the fix?
